// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecoveryFiscal.Infrastructure.Persistence;

#nullable disable

namespace RecoveryFiscal.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RecoveryFiscal.Domain.Entities.ProcessoRecuperacaoFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("atualizado_em_utc");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em_utc");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("criado_por");

                    b.Property<DateOnly>("DataAnalise")
                        .HasColumnType("date")
                        .HasColumnName("data_analise");

                    b.Property<DateOnly>("DataConstituicaoCredito")
                        .HasColumnType("date")
                        .HasColumnName("data_constituicao_credito");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("NifCliente")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("nif_cliente");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nome_cliente");

                    b.Property<string>("NumeroProcesso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numero_processo");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("observacoes");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int")
                        .HasColumnName("prioridade");

                    b.Property<DateTime?>("RemovidoEmUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("removido_em_utc");

                    b.Property<string>("RemovidoPor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("removido_por");

                    b.Property<int>("StatusProcesso")
                        .HasColumnType("int")
                        .HasColumnName("status_processo");

                    b.Property<int>("TipoCredito")
                        .HasColumnType("int")
                        .HasColumnName("tipo_credito");

                    b.Property<decimal>("ValorOriginalCredito")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_original_credito");

                    b.Property<decimal>("ValorRecuperavelEstimado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_recuperavel_estimado");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("NifCliente");

                    b.HasIndex("NomeCliente");

                    b.HasIndex("NumeroProcesso")
                        .IsUnique();

                    b.HasIndex("StatusProcesso", "Prioridade", "DataAnalise");

                    b.ToTable("processos_recuperacao_fiscal", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
